### ISSUE TITLE
Baseline code

### ISSUE THREAD

**Issue by Acedorkz** [YimingWangMingle/liberty#4]
Hi, this is an interesting work. Could you please provide the code for all baselines (ICM, RND, NGU, RIDE) that could be run on this code framework? It would be a great help for reproduction. Have a nice day.

**Comment by Acedorkz** [comment]
Hi, thanks for your response. I have tried to replicate previous baselines on mujoco, but unfortunately, have been unable to reproduce the results presented in Figure 3 and Table 1. Their original code are not designed for mujoco. I truly appreciate your valuable contributions to the community and understand the concerns about the unified project being developed. If possible, sharing just the key code about baselines via email would also be greatly appreciated. Thank you so much for your support!

**Comment by Acedorkz** [comment]
Hi, one question about ppo_agent, when are `update_encoder` and `update_transition_reward_model` called? Thanks.

**Comment by YimingWangMingle** [comment]
Sure, could you please share your email address?

**Comment by Acedorkz** [comment]
Email: acedorkzz@gmail.com. Thanks a lot.

**Comment by YimingWangMingle** [comment]
Hi, you can firstly refer to https://github.com/YimingWangMingle/EME/blob/main/src/habitat-lab/liberty_train.py
